config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :carts
  devise_for :users
  resources :items
  resources :line_items
  root to: 'items#index'
  resources :charges
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :line_items
  has_many :items, through: :line_items

  # before_validation :check_for_other_empty_carts
  #
  # def check_for_other_empty_carts
  #   user = User.find(user_id)
  #   return if user.carts.where(paid: false).blank?
  #
  #   errors.add(:cart, "L'utilisateur dispose déjà d'un panier")
  # end

  def add_product(item)
     current_item = line_items.find_by(item_id: item.id)
     if !current_item
       current_item = line_items.create(item_id: item.id)
     else
       # put a flash message to say that this item is already in the cart
     end
     current_item
  end

  def total_price
    sum = 0
    self.line_items.each_with_index do |line_item, i|
        sum += line_item.item.price
    end
    sum
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :set_cart, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    @cart = Cart.find_by(user_id: current_user.id)
  end
  # def total_price
  #   @cart.line_items.each_with_index do |line_item, i|
  #   += i.line_item.item.price
  # end

  # GET /carts/new
  def new
    @cart = Cart.new
  end

  # GET /carts/1/edit
  def edit
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(cart_params)

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render :show, status: :created, location: @cart }
      else
        format.html { render :new }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /carts/1
  # PATCH/PUT /carts/1.json
  def update
    respond_to do |format|
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { render :show, status: :ok, location: @cart }
      else
        format.html { render :edit }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart.destroy
    respond_to do |format|
      format.html { redirect_to carts_url, notice: 'Cart was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cart
      @cart = Cart.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cart_params
      params.fetch(:cart, {})
    end

app/helpers/carts_helper.rb
module CartsHelper
end

app/views/carts/_form.html.erb
<%= form_with(model: cart, local: true) do |form| %>
  <% if cart.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(cart.errors.count, "error") %> prohibited this cart from being saved:</h2>

      <ul>
      <% cart.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/carts/edit.html.erb
<h1>Editing Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Show', @cart %> |
<%= link_to 'Back', carts_path %>

app/views/carts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Carts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @carts.each do |cart| %>
      <tr>
        <td><%= link_to 'Show', cart %></td>
        <td><%= link_to 'Edit', edit_cart_path(cart) %></td>
        <td><%= link_to 'Destroy', cart, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/carts/new.html.erb
<h1>New Cart</h1>

<%= render 'form', cart: @cart %>

<%= link_to 'Back', carts_path %>

app/views/carts/show.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
    <div class="card" id="show-card">

    <table class="table table-hover table-striped">
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Price</th>
          <th>Image url</th>
          <th>Options</th>
        </tr>
      </thead>
      <tbody>
      <% current_user.cart.line_items.each_with_index do |line_item, i| %>
        <tr>
          <td><strong><%= line_item.item.title %></strong></td>
          <td><%= line_item.item.description %></td>
          <td><%= line_item.item.price %></td>
          <td><img class="rounded" src="<%= line_item.item.image_url %>" style="width:50%"></td>
          <td><button type="button" class="btn btn-secondary btn-sm" id="remove-btn"> <%= link_to "Remove from cart", line_item_path(line_item.id), :method=>:delete, :remote => true %></button></td>
        </tr>
      <% end %>

      </tbody>

    </table>   <div class="card-footer text-right"id="item-total">
    <p>Total: <%= current_user.cart.total_price %> euros<p>

  </div>    
    <div class="d-flex bd-highlight">
    <div class="p-2 flex-fill bd-highlight align-items-end" id="btn-right"><div class="btn btn-success" id="back" ><%= link_to 'Back', items_path %></div></div>
    <div class="p-2 flex-fill bd-highlight align-items-end" id="btn-right"><div class="btn btn-secondary" id="order" ><%= link_to 'Order', new_charge_path%></div></div>
    </div>
        </div>


</div>


    
 
   