config/routes.rb
Rails.application.routes.draw do
  resources :orders
  resources :carts
  devise_for :users
  resources :items
  resources :line_items
  root to: 'items#index'
  resources :charges
end

app/views/layouts/_carts.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-1"></div>
      <div class="col-sm-10">
         </div>
    <div class="col-sm-1"></div>
  </div>
</div>

app/views/layouts/_item.html.erb
<link rel="stylesheet" href="stylesheets/style.css">
<body id="body-items">
<div class="row">
<% @items.each do |item| %>
  <div class="col-md-4 col-md-4 mb-4">
  <div class="card">
          <div class="card-body">
            <img class="card-img-top" src=<%= item.image_url %> alt="Card image cap" style="max-width:50%">
            <h4 class="card-title"style="margin-top:10px" id="item-title"><%= item.title %></h4>
            <h6 class="card-subtitle mb-2 text-muted" id="item-price"><%= item.price %></h6>
            <p class="card-text" ><%= item.description %></p>
            <div id="show"><%= link_to 'Show', item %></div>
          </div>
        </div>
      </div>
<% end %>

</div>
</body>

app/views/layouts/_navbar.html.erb
<link rel="stylesheet" href="stylesheets/style.css">

<nav class="navbar navbar-expand-lg navbar-light " id="nav-color">

  <a class="navbar-brand" id="navbar" <%= link_to "Cats’ Shop", root_path, :class => "dropdown-item" %> </a>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <% if current_user %>

  <a class="navbar-brand" id="cart-title-navabar"<%= link_to "Your cart", cart_path(@cart), :class => "dropdown-item" %> </a>

  <% end %>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
        </li>
      </ul>

      <li class="nav-item dropdown form-inline my-2 my-lg-0" id="cart-title-navabar" style="margin-right:40px">
        <a class="nav-link dropdown-toggle" href="#" id="cart-title-navabar" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
         Profile
        </a>
        <% if current_user == nil %>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown" >
          <a <%= link_to "Login", new_user_session_path, :class => "dropdown-item" %> </a>
          <a <%= link_to "Create Account", new_user_registration_path, :class => "dropdown-item" %> </a>
        </div>
        <% else %>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a <%= link_to "Sign out", destroy_user_session_path, :class => "dropdown-item", method: :delete %> </a>
        </div>
        <% end %>
      </li>
  </div>

</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link href="https://fonts.googleapis.com/css?family=Hepta+Slab:400,500,600,900&display=swap" rel="stylesheet">        <title>OnlineShop</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--<p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p> -->

   <!-- <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %> -->
    <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  </head>

  <body>
  <%= render 'layouts/navbar' %>

    <%= yield %>
  </body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>